import json

f = open("aval-alunos.json")

bd = json.load(f)

f.close()
ttl = '''

@prefix : <http://www.semanticweb.org/35193/ontologies/2024/3/alunos/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.semanticweb.org/35193/ontologies/2024/3/alunos/> .

<http://www.semanticweb.org/35193/ontologies/2024/3/alunos> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#temExame
:temExame rdf:type owl:ObjectProperty ;
          rdfs:domain :Aluno ;
          rdfs:range :Exame .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#temtpc
:temtpc rdf:type owl:ObjectProperty ;
        rdfs:domain :Aluno ;
        rdfs:range :TPC .


#################################################################
#    Data properties
#################################################################

###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#curso
:curso rdf:type owl:DatatypeProperty .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#idAluno
:idAluno rdf:type owl:DatatypeProperty .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#nome
:nome rdf:type owl:DatatypeProperty .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#nota
:nota rdf:type owl:DatatypeProperty .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#nota_projeto
:nota_projeto rdf:type owl:DatatypeProperty .


#################################################################
#    Classes
#################################################################

###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#Aluno
:Aluno rdf:type owl:Class .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#Especial
:Especial rdf:type owl:Class ;
          rdfs:subClassOf :Exame .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#Exame
:Exame rdf:type owl:Class .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#Normal
:Normal rdf:type owl:Class ;
        rdfs:subClassOf :Exame .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#Recurso
:Recurso rdf:type owl:Class ;
         rdfs:subClassOf :Exame .


###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#TPC
:TPC rdf:type owl:Class .

'''

ttl+='''
#################################################################
#    Individuals
#################################################################

'''

for aluno in bd["alunos"]:
    ttl += f'''
###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#{aluno['idAluno']}
:{aluno['idAluno']} rdf:type owl:NamedIndividual ,
                  :Aluno ;
         :temExame :{aluno['idAluno']}_exame_especial ,
                   :{aluno['idAluno']}_exame_normal ,
                   :{aluno['idAluno']}_exame_recurso ;'''
    for tpc in aluno['tpc']:
        ttl+=f'''
         :temtpc :{aluno['idAluno']}_{tpc['tp']} ;'''
    
    ttl+=f'''
         :curso "{aluno['curso']}" ;
         :idAluno "{aluno['idAluno']}" ;
         :nome "{aluno['nome']}" ;
         :nota_projeto {aluno['projeto']} .
         '''
    if 'normal' in aluno['exames']:
        ttl+=f'''
        
###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#{aluno['idAluno']}_exame_normal
:{aluno['idAluno']}_exame_normal rdf:type owl:NamedIndividual ,
                               :Normal ;
                      :nota {aluno['exames']['normal']} .
        '''

    if 'recurso' in aluno['exames']:
        ttl+=f'''

###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#{aluno['idAluno']}_exame_recurso
:{aluno['idAluno']}_exame_recurso rdf:type owl:NamedIndividual ,
                                 :Recurso ;
                        :nota {aluno['exames']['recurso']} .'''
    if 'especial' in aluno['exames']:
        ttl+=f'''
###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#{aluno['idAluno']}_exame_especial
:{aluno['idAluno']}_exame_especial rdf:type owl:NamedIndividual ,
                                :Especial ;
                       :nota {aluno['exames']['especial']} .
'''
    for tpc in aluno['tpc']:
        ttl+=f'''
###  http://www.semanticweb.org/35193/ontologies/2024/3/alunos#{aluno['idAluno']}_{tpc['tp']}
:{aluno['idAluno']}_{tpc['tp']} rdf:type owl:NamedIndividual ,
                       :TPC ;
              :nota {tpc['nota']} .
'''
    
ttl+='''###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi'''

with open("onto.ttl","w") as f2:
    f2.write(ttl)
